# Generated by Django 5.0.14 on 2025-11-16 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communities/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('members', models.ManyToManyField(blank=True, related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='communities_slug_81f3ae_idx'), models.Index(fields=['-created_at'], name='communities_created_54da6c_idx')],
            },
        ),
    ]
