# Generated by Django 5.0.14 on 2025-12-16 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(db_index=True, help_text='Заголовок поста (5-300 символов)', max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Основной текст поста', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован')),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество просмотров')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Закрепленные посты отображаются в начале списка', verbose_name='Закреплен')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(help_text='Название сообщества (3-200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL', max_length=200, unique=True, verbose_name='URL идентификатор')),
                ('description', models.TextField(help_text='Подробное описание сообщества', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='communities/avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Аватар сообщества')),
                ('is_private', models.BooleanField(db_index=True, default=False, verbose_name='Приватное сообщество')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='posts_commu_slug_b53368_idx'), models.Index(fields=['is_private', '-created_at'], name='posts_commu_is_priv_a8f363_idx'), models.Index(fields=['-created_at'], name='community_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.CheckConstraint(check=models.Q(('title__regex', '.{3,}')), name='community_title_min_length'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.community', verbose_name='Сообщество'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at', 'author'], name='post_created_author_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='post_community_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views_count'], name='post_views_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-created_at'], name='post_published_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='post_pinned_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('title__regex', '.{5,}')), name='post_title_min_length'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('views_count__gte', 0)), name='post_views_positive'),
        ),
    ]
