# Generated by Django 5.0.14 on 2025-11-16 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Заголовок')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'is_published'], name='posts_post_created_328ac0_idx'), models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'), models.Index(fields=['community', '-created_at'], name='posts_post_communi_ddf459_idx')],
            },
        ),
    ]
